# Generated by Django 5.0.6 on 2024-11-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photo_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
