# Generated by Django 5.0.6 on 2024-12-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_photo_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
